language: c
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4052245BD4284CDD
  - echo "deb https://repo.iovisor.org/apt/$(lsb_release -cs) $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/iovisor.list
  - sudo apt-get update
  - sudo apt-get install bcc-tools libbcc-examples linux-headers-$(uname -r)
addons:
  apt:
    packages:
      - util-linux
      - rake
      - psmisc
      - bison
      - git
      - gperf
      - autotools-dev
compiler:
  - gcc
  - clang
env:
  - MRUBY_VERSION=2.0.1
  - MRUBY_VERSION=2.0.0
  - MRUBY_VERSION=master
script:
  - rake
  # - rake test
branches:
  only:
    - master

matrix:
  allow_failures:
    - env: ["MRUBY_VERSION=2.0.1"]